version: "3.8"
services:
  mc:
    restart: unless-stopped
    build: "minecraft-server"
    ports:
      - 25565:25565/tcp
      - 19132:19132/udp
    volumes:
      - ${PWD}/volumes/mc:/papermc
    environment:
      - MC_VERSION=1.16.3
    stdin_open: true
    tty: true
  dns:
    restart: unless-stopped
    image: jpillora/dnsmasq
    ports:
      - 53:53/udp
      - 5380:8080
    volumes:
      - ${PWD}/dnsmasq.conf:/etc/dnsmasq.conf
    cap_add:
      - NET_ADMIN
    environment: 
      - HTTP_USER=foo
      - HTTP_PASS=bar